### ISSUE TITLE
Error installing mixture

### ISSUE THREAD

**Issue by n477h4n** [smarie/python-mixture#12]
Hi,
I'm trying to install mixture python package using pip (python 2.7) and I get this message:

" egg_info --egg-base /tmp/pip-pip-egg-info-bWuVyO
             cwd: /tmp/pip-wheel-VXPMkm/pandoc/
        Complete output (6 lines):
        Traceback (most recent call last):
          File "<string>", line 1, in <module>
          File "/tmp/pip-wheel-VXPMkm/pandoc/setup.py", line 11
            error = f"pip is not installed, refer to <{url}> for instructions."
                                                                              ^
        SyntaxError: invalid syntax "

Actually, the message is bigger than this, but I don't know how to solve, I've tried to download mixture-0.2.1.tar.gz, and I keep getting the same message.

How can I solve this problem and install the python-mixture?

Edit 1: I'm using ubuntu 20.04

(Sorry for bad English, I'm from Brasil)

**Comment by smarie** [comment]
Hi @n477h4n thanks for the feedback ! Unfortunately this project was never really maintained/filled with contents. Originally I had a huge list of mix-ins created in internal projects (for my job) that I had planned to properly put in such a lib.

However it appeared that most users (including myself) were more interested in creating classes easily with all mix-ins included, rather than being able to use them one by one. Therefore I ended up focusing my efforts on https://smarie.github.io/python-pyfields/ .

So all that is left here at the moment is the `@apply_mixins` decorator. Are you interested in using it and / or contribute in the lib by proposing a few reusable mix-in classes ? If this is the case, we should first update the project template so that it works again. The latest version of the template that I use in all my python libs uses nox and github actions.

**Comment by n477h4n** [comment]
Hi,
Thanks for the rapid answer, but i have used this lib on some work with my collegues, when we were developing a python script to look for kinematical substrutures on galaxy clusters and i've tried to run the same script and that error appeared.

I'm little busy with my phd and classes, but thanks for the help.

**Comment by smarie** [comment]
Ok - you can at least workaround by copying the source code for now since it is supposed to be python 2 compliant if I remember well.
